import assert from "node:assert/strict";
const P = "/Users/yrolland/Documents/GitHub/protocole-app/packages/core/src";
const { recommendTargets, splitDelta, isPalierEntry, lastPalier, PALIER } = await import(`${P}/palier.js`);
const { recompZone } = await import(`${P}/tdee.js`);
const { buildCoachPrompt } = await import(`${P}/coach/prompt.js`);
const { DEFAULT_TARGETS } = await import(`${P}/targets.js`);
const { SCHEMES } = await import(`${P}/climbing.js`);
const { shiftDateKey } = await import(`${P}/dateUtils.js`);
let n = 0; const ok = (c, m) => { assert.ok(c, m); n++; };
const T = { protein: 200, carbs: 280, fat: 90, fiber: 35 }; // cibles réelles de Yoann après sa retouche (2800)
const reading = (d) => ({ status: "ok", reading: { deficit: d, ...recompZone(d) } });
const recomp = (a, b = a) => ({ j14: reading(a), j21: reading(b) });
const trend = (d1, d2) => ({ deltaWeek: d1, deltaWeekPrev: d2 });
const now = new Date(2026, 9, 2, 10, 0);
const run = (o) => recommendTargets({ now, targets: T, targetHistory: [], loggedRate7: 1, ...o });
let r = run({ recomp: recomp(600), trend: trend(-0.2, -0.1) });
ok(r.action === "up" && r.deltaKcal === 100 && r.proposed.protein === 200 && r.proposed.carbs === 300 && r.proposed.fat === 95 && r.proposed.kcal === 2925, `déficit 600 → +100 : ${JSON.stringify(r.proposed)}`);
ok(run({ recomp: recomp(400), trend: trend(-0.2, -0.1) }).deltaKcal === 100, "déficit 400 → +100");
ok(run({ recomp: recomp(250), trend: trend(-0.4, -0.45) }).deltaKcal === 100, "perte rapide → +100");
r = run({ recomp: recomp(-50), trend: trend(0.1, 0.2) });
ok(r.deltaKcal === -100 && r.proposed.carbs === 260 && r.proposed.fat === 85, `surplus → −100 : G ${r.proposed.carbs} L ${r.proposed.fat}`);
ok(PALIER.MAX_STEP === 100 && splitDelta(100, T).carbs === 300, "plafond 100, split +100 → +20 G / +5 L");
ok(!isPalierEntry({ date: "2026-10-02", kcal: 2800 }, undefined), "ancienne entrée isolée sans repère → pas un palier");
ok(!isPalierEntry({ date: "2026-10-02", kcal: 2800, prevKcal: 2800 }), "net 0 → pas un palier");
ok(!isPalierEntry({ date: "2026-10-02", kcal: 2860, prevKcal: 2800 }), "net +60 → pas un palier");
ok(isPalierEntry({ date: "2026-10-02", kcal: 2900, prevKcal: 2800 }), "net +100 → palier");
ok(isPalierEntry({ date: "2026-10-02", kcal: 2900, source: "palier" }), "appliqué depuis la carte → palier");
ok(isPalierEntry({ date: "2026-10-02", kcal: 2950 }, { date: "2026-09-20", kcal: 2800 }), "sans prevKcal, delta vs entrée précédente ≥ 100 → palier");
const fake = [{ date: "2026-10-02", kcal: 2800, prevKcal: 2800, source: "manual" }];
ok(lastPalier(fake) === null && run({ recomp: recomp(600), trend: trend(-0.2, -0.1), targetHistory: fake }).action === "up", "retouche à total constant : pas d'observation, +100 proposé");
const real = [{ date: shiftDateKey("2026-10-02", -3), kcal: 2900, prevKcal: 2800, source: "palier" }, ...fake];
r = run({ recomp: recomp(600), trend: trend(-0.2, -0.1), targetHistory: real });
ok(r.action === "hold" && /J\+3\/14/.test(r.blocked), "vrai palier J−3 → observation");
const base = { weight: [], sleep: [], training: [], knee: [], macros: [], notes: [], steps: [], targets: DEFAULT_TARGETS, foodLog: [], foodOverrides: {}, profile: "", journal: "", scheme: SCHEMES.gym, basketSchedule: { weekly: [], matchDates: [] }, weeklyPlan: [], energy: null, matchWeek: false };
const u = buildCoachPrompt({ ...base, phase: "recomposition", targetHistory: real }, "").user;
const summary = JSON.parse(u.split("RÉSUMÉ 14 JOURS (moyennes fiables, tendance de fond) :\n")[1].split("\n\nJOUR PAR JOUR")[0]);
ok(summary.paliers?.length === 1 && summary.paliers[0].source === "palier", "coach : 1 vrai palier sur 2 entrées");
ok(!buildCoachPrompt({ ...base, phase: "seche", targetHistory: fake }, "").user.includes("PALIERS"), "sèche + fausse entrée : aucun bloc paliers");
console.log(`${n} assertions OK`);
